// Generated by CoffeeScript 1.8.0
(function() {
  var $, app;

  $ = window.jQuery;

  app = window.gifDropAdmin = {
    init: function() {
      return $('#gifdrop-path').keypress(function(e) {
        var allowed, key, keyString;
        key = e.which;
        keyString = String.fromCharCode(key);
        allowed = /^[a-zA-Z0-9\/-]$/;
        if (!(key === 0 || key === 8 || keyString === '' || keyString.match(allowed))) {
          return false;
        }
      });
    }
  };

  $(function() {
    return app.init();
  });

}).call(this);
