// Generated by CoffeeScript 1.8.0
(function() {
  var $, app;

  $ = window.jQuery;

  app = window.gifDropAdmin = {
    init: function() {
      return $('#gifdrop-path').keypress(function(e) {
        var key;
        key = e.which;
        console.log(key);
        if (!(key === 45 || key === 47 || key === 13 || (96 < key && key < 123) || (47 < key && key < 58))) {
          return false;
        }
      });
    }
  };

  $(function() {
    return app.init();
  });

}).call(this);
